image: python:3.6

sanitycheck:
  script:
  - python setup.py install
  - bztogl --help
  - phabtogl --help

lint:
  script:
  - pip install flake8
  - flake8 .

unittests:
  script:
  - python setup.py pytest
